export const TOPIC_DATABASE: Record<string, string[]> = {
  Physics: [
    'Kinematics', 'Laws of Motion', 'Work, Energy & Power', 'Rotational Motion',
    'Gravitation', 'Thermodynamics', 'Electrostatics', 'Current Electricity',
    'Magnetism', 'Optics', 'Modern Physics', 'Semiconductors',
  ],
  Chemistry: [
    'Atomic Structure', 'Chemical Bonding', 'Thermodynamics', 'Equilibrium',
    'Redox Reactions', 'Hydrogen', 's-Block Elements', 'p-Block Elements',
    'Organic Chemistry - Basic Principles', 'Hydrocarbons', 'Haloalkanes',
    'Alcohols & Phenols', 'Aldehydes & Ketones', 'Amines', 'Biomolecules',
  ],
  Biology: [
    'Diversity in Living World', 'Structural Organisation', 'Cell Structure & Function',
    'Plant Physiology', 'Human Physiology', 'Reproduction', 'Genetics & Evolution',
    'Biology in Human Welfare', 'Biotechnology', 'Ecology',
  ],
  Mathematics: [
    'Sets & Functions', 'Trigonometry', 'Complex Numbers', 'Quadratic Equations',
    'Permutations & Combinations', 'Binomial Theorem', 'Sequences & Series',
    'Straight Lines', 'Conic Sections', 'Limits & Derivatives', 'Probability',
    'Matrices & Determinants', 'Calculus', 'Vectors', '3D Geometry',
  ],
  English: ['Reading Comprehension', 'Grammar', 'Vocabulary', 'Writing Skills', 'Literature'],
  'General Knowledge': ['History', 'Geography', 'Polity', 'Economics', 'Current Affairs'],
  Reasoning: ['Verbal Reasoning', 'Non-Verbal Reasoning', 'Analytical Reasoning', 'Data Interpretation'],
  Quant: ['Number System', 'Arithmetic', 'Algebra', 'Geometry', 'Mensuration'],
  'Legal Reasoning': ['Torts', 'Contracts', 'Criminal Law', 'Constitution', 'Legal GK'],
  History: ['Ancient India', 'Medieval India', 'Modern India', 'World History'],
  Geography: ['Physical Geography', 'Indian Geography', 'World Geography'],
  Economics: ['Microeconomics', 'Macroeconomics', 'Indian Economy'],
  Accountancy: ['Accounting for Partnership', 'Company Accounts', 'Financial Statements', 'Computerised Accounting'],
  'Business Studies': ['Nature of Management', 'Principles of Management', 'Business Environment', 'Planning', 'Organising'],
  'Logical Reasoning': ['Analogies', 'Series Completion', 'Blood Relations', 'Syllogisms', 'Coding-Decoding'],
  'Quantitative Techniques': ['Percentages', 'Averages', 'Ratios', 'Profit & Loss', 'Simple & Compound Interest'],
  'Current Affairs': ['National News', 'International Affairs', 'Sports', 'Awards & Honours', 'Government Schemes'],
  Awareness: ['Indian Polity', 'Indian History', 'Geography', 'Science & Technology', 'Current Events'],
  GK: ['General Science', 'History', 'Geography', 'Polity', 'Current Affairs'],
  Logic: ['Logical Deduction', 'Verbal Ability', 'Critical Reasoning', 'Puzzles'],
  GAT: ['English', 'General Knowledge', 'Science', 'Geography', 'Current Affairs'],
  'Elementary Mathematics': ['Arithmetic', 'Algebra', 'Geometry', 'Trigonometry', 'Statistics'],
  'GS Paper 1': ['History', 'Geography', 'Indian Polity', 'Economics', 'Environment', 'Science & Tech'],
  CSAT: ['Comprehension', 'Logical Reasoning', 'Analytical Ability', 'Decision Making', 'Data Interpretation'],
  'General Test': ['General Knowledge', 'Numerical Ability', 'Logical Reasoning', 'Language', 'Quantitative Reasoning'],
  'Social Science': ['History', 'Geography', 'Political Science', 'Economics'],
  Hindi: ['Prose', 'Poetry', 'Grammar', 'Writing'],
  'Regional Language': ['Prose', 'Poetry', 'Grammar', 'Comprehension'],
  'Computer Science': ['Programming Basics', 'Data Structures', 'Databases', 'Networking', 'Boolean Algebra'],
  'Political Science': ['Constitution', 'Indian Government', 'International Relations', 'Political Theory'],
  Science: ['Physics Basics', 'Chemistry Basics', 'Biology Basics', 'Environmental Science'],
  'Maths/Bio': ['Mathematics', 'Biology', 'Quantitative Aptitude'],
  MBA: ['Verbal Ability', 'Quantitative Aptitude', 'Logical Reasoning', 'Data Interpretation'],
  MCA: ['Mathematics', 'Computer Science', 'Logical Reasoning', 'English'],
  General: ['General Knowledge', 'Current Affairs', 'Reasoning', 'Quantitative Aptitude'],
};
